### PR TITLE
add settings.py

### PR DESCRIPTION
**Pull request by Junefen**
Define the Configure class to parse any INI file in local or remote server.

- Get option's value 
- Add option
- Update option
- Delete option
- Delete file

### CODE REVIEW

**Review by eko999 — COMMENTED** [review]
There are two key points:
1.  How to set a variable as the class' attribute by `setattr`?  for us, it should be: how to add the section and its value as the class's attributes.
```
for key in self.config._sections.keys():
            setattr(self, key, getattr(self.config._sections, key))
```
2. How to get the value from the class attributes? there are two ways to do this:
1). use the dict_type for ConfigParser
```
class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self

config = ConfigParser(dict_type=AttrDict)
config.read('provision.ini')
print(config.vcenter.server)
```
2). use the `getattr` get to the attribute value, it's more complex

**Comment by eko999** [comment]
so the demo implement is draft as:
```
import os
from configparser import ConfigParser


class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self


class Configure:
    def __init__(self, local_file, remote_ssh=None, remote_file=None):
        self.local_file = local_file
        self.remote_file = remote_file
        self.remote_ssh = remote_ssh
        self.config = ConfigParser(dict_type=AttrDict)
        self.config.read(self.local_file)
        self.save()

    def save(self):
        for key in self.config._sections.keys():
            setattr(self, key, getattr(self.config._sections, key))
        with open(self.local_file, 'w') as f:
            self.config.write(f, space_around_delimiters=False)
        if self.remote_ssh and self.remote_file:
            self.remote_ssh.put_file(self.local_file, self.remote_file)

    def update(self, section, option, value):
        if not self.config.has_section(section):
            self.config.add_section(section)
        self.config.set(section, option, value)
        self.save()

    def delete(self, section, option):
        self.config.remove_option(section, option)
        self.save()


DEPLOY_DATA = os.path.join(os.path.realpath(os.path.join(
    os.path.dirname(__file__),
    os.pardir)),
    "provision.ini"
    )

TEST_DATA = os.path.join(os.path.realpath(os.path.join(
    os.path.dirname(__file__),
    os.pardir)),
    "virtwho.properties"
    )

deploy = Configure(DEPLOY_DATA)
config = Configure(TEST_DATA)
```

**Comment by Junefen** [comment]
Define update() and delete() functions able to add and remove section.
Because we need to add/delete section for /etc/virt-who.conf

```
    def update(self, section, option, value):
        if not self.config.has_section(section):
            self.config.add_section(section)
        self.config.set(section, option, value)
        self.save()

    def delete(self, section, option=None):
        if option is None:
            self.config.remove_section(section)
        else:
            self.config.remove_option(section, option)
        self.save()
```

**Review by eko999 — APPROVED** [review]
Looks good :+1:

**Pull request merged**
